"use strict";
const bcrypt = require("bcrypt");
const { SALT_ROUNDS } = require("../config/constants");

module.exports = {
  up: async (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert(
      "players",
      [
        {
          name: "Djimo",
          email: "djimo@djimo.com",
          password: bcrypt.hashSync("q", SALT_ROUNDS),
          inGame: true,
          img: null,
          build: null,
          ability: null,
          moneyCash: 2,
          egg: 1,
          feather: 1,
          bug: 2,
          vPoint: 3,
          mMarket: 1,
          rMarket: 3,
          vMarket: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
          gameId: 1,
        },
        {
          name: "Jan",
          email: "jan@jan.com",
          password: bcrypt.hashSync("q", SALT_ROUNDS),
          inGame: true,
          img: null,
          build: null,
          ability: null,
          moneyCash: 7,
          egg: 4,
          feather: 1,
          bug: 2,
          vPoint: 2,
          mMarket: 1,
          rMarket: 1,
          vMarket: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
          gameId: 1,
        },
        {
          name: "Jochem",
          email: "jochem@jochem.com",
          password: bcrypt.hashSync("q", SALT_ROUNDS),
          inGame: true,
          img: null,
          build: null,
          ability: null,
          moneyCash: 2,
          egg: 1,
          feather: 1,
          bug: 2,
          vPoint: 3,
          mMarket: 1,
          rMarket: 3,
          vMarket: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
          gameId: 1,
        },
        {
          name: "Joep",
          email: "joep@joep.com",
          password: bcrypt.hashSync("q", SALT_ROUNDS),
          inGame: false,
          img: null,
          build: null,
          ability: null,
          moneyCash: null,
          egg: null,
          feather: null,
          bug: null,
          vPoint: null,
          mMarket: null,
          rMarket: null,
          vMarket: null,
          createdAt: new Date(),
          updatedAt: new Date(),
          gameId: null,
        },
      ],
      {}
    );
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("games", null, {});
  },
};
